name: PR Commit Message Update

on:
  pull_request:

jobs:
  update-commit-message:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set the output
      uses: actions/github-script@v7
      with:
        script: |
          const { data: pr } = await github.rest.pulls.get({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.issue.number
          });

          // PR description
          const description = pr.body || "";

          // Check if "--- commit logs ---" exists
          const marker = "--- commit logs ---";
          const command = 'git log --format="* %s" origin/${{ github.event.pull_request.base.ref }}..${{ github.event.pull_request.head.sha }} --reverse';
          const { stdout: commitLogs } = await exec.getExecOutput(command);

          let newDescription;
          const markerIndex = description.indexOf(marker);
          if (markerIndex !== -1) {
            // If marker exists, replace everything after it
            newDescription = description.substring(0, markerIndex + marker.length) + "\n" + commitLogs;
          } else {
            // If marker doesn't exist, append it to the description
            newDescription = description + "\n\n" + marker + "\n" + commitLogs;
          }

          // Output the new description
          core.setOutput("new_description", newDescription);

          // Update the PR with the new description
          await github.rest.pulls.update({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.issue.number,
            body: newDescription
          });
        github-token: ${{ secrets.GITHUB_TOKEN }}
